config/routes.rb
Gt::Application.routes.draw do
  resources :commits

  resources :pull_requests

end

app/models/commit.rb
class Commit < ActiveRecord::Base
  belongs_to :pull_request

  validates :test_pushed, inclusion: { in: [true, false] }
  validates :sha, length: { is: 40 }
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  validates_uniqueness_of :number
  
  has_many :commits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_action :set_commit, only: [:show, :edit, :update, :destroy]

  # GET /commits
  # GET /commits.json
  def index
    @commits = Commit.all
  end

  # GET /commits/1
  # GET /commits/1.json
  def show
  end

  # GET /commits/new
  def new
    @commit = Commit.new
  end

  # GET /commits/1/edit
  def edit
  end

  # POST /commits
  # POST /commits.json
  def create
    @commit = Commit.new(commit_params)

    respond_to do |format|
      if @commit.save
        format.html { redirect_to @commit, notice: 'Commit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @commit }
      else
        format.html { render action: 'new' }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commits/1
  # PATCH/PUT /commits/1.json
  def update
    respond_to do |format|
      if @commit.update(commit_params)
        format.html { redirect_to @commit, notice: 'Commit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commits/1
  # DELETE /commits/1.json
  def destroy
    @commit.destroy
    respond_to do |format|
      format.html { redirect_to commits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commit
      @commit = Commit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commit_params
      params.require(:commit).permit(:test_pushed, :sha)
    end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  before_action :set_pull_request, only: [:show, :edit, :update, :destroy]

  # GET /pull_requests
  # GET /pull_requests.json
  def index
    @pull_requests = PullRequest.all
  end

  # GET /pull_requests/1
  # GET /pull_requests/1.json
  def show
  end

  # GET /pull_requests/new
  def new
    @pull_request = PullRequest.new
  end

  # GET /pull_requests/1/edit
  def edit
  end

  # POST /pull_requests
  # POST /pull_requests.json
  def create
    @pull_request = PullRequest.new(pull_request_params)

    respond_to do |format|
      if @pull_request.save
        format.html { redirect_to @pull_request, notice: 'PullRequest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pull_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @pull_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pull_requests/1
  # PATCH/PUT /pull_requests/1.json
  def update
    respond_to do |format|
      if @pull_request.update(pull_request_params)
        format.html { redirect_to @pull_request, notice: 'PullRequest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pull_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pull_requests/1
  # DELETE /pull_requests/1.json
  def destroy
    @pull_request.destroy
    respond_to do |format|
      format.html { redirect_to pull_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pull_request
      @pull_request = PullRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pull_request_params
      params.require(:pull_request).permit(:number)
    end
end

app/controllers/pullrequests_controller.rb
class PullrequestsController < ApplicationController
  before_action :set_pullrequest, only: [:show, :edit, :update, :destroy]

  # GET /pullrequests
  # GET /pullrequests.json
  def index
    @pullrequests = Pullrequest.all
  end

  # GET /pullrequests/1
  # GET /pullrequests/1.json
  def show
  end

  # GET /pullrequests/new
  def new
    @pullrequest = Pullrequest.new
  end

  # GET /pullrequests/1/edit
  def edit
  end

  # POST /pullrequests
  # POST /pullrequests.json
  def create
    @pullrequest = Pullrequest.new(pullrequest_params)

    respond_to do |format|
      if @pullrequest.save
        format.html { redirect_to @pullrequest, notice: 'Pullrequest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pullrequest }
      else
        format.html { render action: 'new' }
        format.json { render json: @pullrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pullrequests/1
  # PATCH/PUT /pullrequests/1.json
  def update
    respond_to do |format|
      if @pullrequest.update(pullrequest_params)
        format.html { redirect_to @pullrequest, notice: 'Pullrequest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pullrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pullrequests/1
  # DELETE /pullrequests/1.json
  def destroy
    @pullrequest.destroy
    respond_to do |format|
      format.html { redirect_to pullrequests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pullrequest
      @pullrequest = Pullrequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pullrequest_params
      params.require(:pullrequest).permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
end

app/views/commits/_form.html.erb
<%= form_for(@commit) do |f| %>
  <% if @commit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit.errors.count, "error") %> prohibited this commit from being saved:</h2>

      <ul>
      <% @commit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_pushed %><br>
    <%= f.text_field :test_pushed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commits/edit.html.erb
<h1>Editing commit</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit %> |
<%= link_to 'Back', commits_path %>

app/views/commits/index.html.erb
<h1>Listing commits</h1>

<table>
  <thead>
    <tr>
      <th>Test pushed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commits.each do |commit| %>
      <tr>
        <td><%= commit.test_pushed %></td>
        <td><%= link_to 'Show', commit %></td>
        <td><%= link_to 'Edit', edit_commit_path(commit) %></td>
        <td><%= link_to 'Destroy', commit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commit', new_commit_path %>

app/views/commits/new.html.erb
<h1>New commit</h1>

<%= render 'form' %>

<%= link_to 'Back', commits_path %>

app/views/commits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test pushed:</strong>
  <%= @commit.test_pushed %>
</p>

<%= link_to 'Edit', edit_commit_path(@commit) %> |
<%= link_to 'Back', commits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pull_requests/_form.html.erb
<%= form_for(@pull_request) do |f| %>
  <% if @pull_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pull_request.errors.count, "error") %> prohibited this pull_request from being saved:</h2>

      <ul>
      <% @pull_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pull_requests/edit.html.erb
<h1>Editing pull_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @pull_request %> |
<%= link_to 'Back', pull_requests_path %>

app/views/pull_requests/index.html.erb
<h1>Listing Pull Requests</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pull_requests.each do |pull_request| %>
      <tr>
        <td><%= pull_request.number %></td>
        <td><%= link_to 'Show', pull_request %></td>
        <td><%= link_to 'Edit', edit_pull_request_path(pull_request) %></td>
        <td><%= link_to 'Destroy', pull_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pullrequest', new_pull_request_path %>

app/views/pull_requests/new.html.erb
<h1>New pull_request</h1>

<%= render 'form' %>

<%= link_to 'Back', pull_requests_path %>

app/views/pull_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @pull_request.number %>
</p>

<%= link_to 'Edit', edit_pull_request_path(@pull_request) %> |
<%= link_to 'Back', pull_requests_path %>